#!/bin/sh
set -e
echo $'\n\n\n\n\n'
javac -cp .:tester.jar Tweets.java
	echo $'Tweets.java compiled successfully\n'
javac -cp .:tester.jar Queries.java
	echo $'Queries.java compiled successfully\n'
javac -cp .:tester.jar TweetList.java
	echo $'TweetList.java compiled successfully\n'
javac -cp .:tester.jar SampleTweets.java
	echo $'SampleTweets.java compiled successfully\n'
javac -cp .:tester.jar FilterTweets.java
	echo $'FilterTweets.java compiled successfully\n'
