#!/bin/bash
set -e
echo $'\n\n\n\n\n'
javac -cp .:tester.jar Tweets.java
	echo $'Tweets.java compiled successfully\n'
javac -cp .:tester.jar Queries.java
	echo $'Queries.java compiled successfully\n'
javac -cp .:tester.jar TweetList.java
	echo $'TweetList.java compiled successfully\n'
javac -cp .:tester.jar SampleTweets.java
	echo $'SampleTweets.java compiled successfully\n'
javac -cp .:tester.jar FilterTweets.java
	echo $'FilterTweets.java compiled successfully\n'

# Run FilterTweets if 1 is passed
if [ $1 -eq 1 ]
then 
  java FilterTweets html > test.html
  echo $'Opening test.html in 3...\n'
  sleep 1
  echo "2..."
  sleep 1
  echo "1..."
  sleep 1
  xdg-open test.html
fi
