#!/bin/bash

echo $'\n\n\n\n\n'
javac -cp .:tester.jar Tweets.java
	echo $'Tweets.java compiled successfully\n'
javac -cp .:tester.jar Queries.java
	echo $'Queries.java compiled successfully\n'
javac -cp .:tester.jar ExampleQueries.java
	echo $'ExampleQueries.java compiled successfully\n'
javac -cp .:tester.jar TweetList.java
	echo $'TweetList.java compiled successfully\n'
javac -cp .:tester.jar SampleTweets.java
	echo $'SampleTweets.java compiled successfully\n'
javac -cp .:tester.jar FilterTweets.java
	echo $'FilterTweets.java compiled successfully\n'

# Run ExampleQueries if ex is passed
if [ "$1" == "ex" ]; then
  java -cp $LIB/public/tester-2.3.jar:. tester.Main ExampleQueries
fi

# Run FilterTweets if commands are passed
if [ "$1" == "html" ]; then
  java FilterTweets html "$2" "$3" > test.html
elif [ "$1" == "count" ]; then
  java FilterTweets count $2 $3
fi

